-- ============================================================
-- Customer Intelligence Analytics Platform
-- ANALYTICS - Executive KPIs
-- Grain: one row for the observed snapshot
-- ============================================================

USE ROLE CUSTOMER_INTELLIGENCE_ROLE;
USE WAREHOUSE CUSTOMER_INTELLIGENCE_WH;
USE DATABASE CUSTOMER_INTELLIGENCE;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW
    CUSTOMER_INTELLIGENCE.ANALYTICS.VW_EXECUTIVE_KPIS AS

SELECT

    SNAPSHOT_QUARTER,

    -- Customer base
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,

    COUNT_IF(CUSTOMER_STATUS = 'Stayed') AS STAYED_CUSTOMERS,
    COUNT_IF(CUSTOMER_STATUS = 'Joined') AS JOINED_CUSTOMERS,
    COUNT_IF(CHURN_FLAG = 1) AS CHURNED_CUSTOMERS,

    -- Churn
    ROUND(
        COUNT_IF(CHURN_FLAG = 1)
        / NULLIF(COUNT(DISTINCT CUSTOMER_ID), 0),
        4
    ) AS CHURN_RATE,

    -- Financial performance
    ROUND(SUM(MONTHLY_CHARGE), 2) AS TOTAL_MONTHLY_CHARGES,
    ROUND(AVG(MONTHLY_CHARGE), 2) AS AVG_MONTHLY_CHARGE,

    ROUND(SUM(TOTAL_REVENUE), 2) AS TOTAL_REVENUE,
    ROUND(AVG(TOTAL_REVENUE), 2) AS AVG_TOTAL_REVENUE_PER_CUSTOMER,

    -- Observed revenue associated with customers who churned
    ROUND(
        SUM(IFF(CHURN_FLAG = 1, MONTHLY_CHARGE, 0)),
        2
    ) AS CHURNED_MONTHLY_REVENUE,

    ROUND(
        SUM(IFF(CHURN_FLAG = 1, TOTAL_REVENUE, 0)),
        2
    ) AS CHURNED_HISTORICAL_REVENUE,

    -- Customer value
    ROUND(AVG(CLTV), 2) AS AVG_CLTV,

    COUNT_IF(HIGH_VALUE_FLAG = 1) AS HIGH_VALUE_CUSTOMERS,

    ROUND(
        COUNT_IF(HIGH_VALUE_FLAG = 1 AND CHURN_FLAG = 1)
        / NULLIF(COUNT_IF(HIGH_VALUE_FLAG = 1), 0),
        4
    ) AS HIGH_VALUE_CHURN_RATE,

    -- Lifecycle / experience
    ROUND(AVG(TENURE_IN_MONTHS), 2) AS AVG_TENURE_MONTHS,
    ROUND(AVG(SATISFACTION_SCORE), 2) AS AVG_SATISFACTION_SCORE

FROM CUSTOMER_INTELLIGENCE.CORE.CUSTOMER_360_VIEW

GROUP BY SNAPSHOT_QUARTER;