-- ============================================================
-- Customer Intelligence Analytics Platform
-- ANALYTICS - Product Adoption Depth
-- Grain: one row per total service count
-- ============================================================

USE ROLE CUSTOMER_INTELLIGENCE_ROLE;
USE WAREHOUSE CUSTOMER_INTELLIGENCE_WH;
USE DATABASE CUSTOMER_INTELLIGENCE;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW
    CUSTOMER_INTELLIGENCE.ANALYTICS.VW_PRODUCT_DEPTH AS

WITH BASE AS (

    SELECT *
    FROM CUSTOMER_INTELLIGENCE.CORE.CUSTOMER_360_VIEW

),

OVERALL AS (

    SELECT
        COUNT_IF(CHURN_FLAG = 1)
        / NULLIF(COUNT(DISTINCT CUSTOMER_ID), 0)
        AS OVERALL_CHURN_RATE
    FROM BASE

)

SELECT

    b.TOTAL_SERVICE_COUNT,

    COUNT(DISTINCT b.CUSTOMER_ID) AS CUSTOMERS,

    ROUND(
        COUNT(DISTINCT b.CUSTOMER_ID)
        / SUM(COUNT(DISTINCT b.CUSTOMER_ID)) OVER (),
        4
    ) AS CUSTOMER_SHARE,

    COUNT_IF(b.CHURN_FLAG = 1) AS CHURNED_CUSTOMERS,

    ROUND(
        COUNT_IF(b.CHURN_FLAG = 1)
        / NULLIF(COUNT(DISTINCT b.CUSTOMER_ID), 0),
        4
    ) AS CHURN_RATE,

    ROUND(
        (
            COUNT_IF(b.CHURN_FLAG = 1)
            / NULLIF(COUNT(DISTINCT b.CUSTOMER_ID), 0)
        )
        / NULLIF(MAX(o.OVERALL_CHURN_RATE), 0),
        2
    ) AS CHURN_INDEX,

    ROUND(AVG(b.TENURE_IN_MONTHS), 2) AS AVG_TENURE_MONTHS,

    ROUND(AVG(b.MONTHLY_CHARGE), 2) AS AVG_MONTHLY_CHARGE,

    ROUND(AVG(b.TOTAL_REVENUE), 2) AS AVG_TOTAL_REVENUE,

    ROUND(AVG(b.CLTV), 2) AS AVG_CLTV

FROM BASE b

CROSS JOIN OVERALL o

GROUP BY b.TOTAL_SERVICE_COUNT

ORDER BY b.TOTAL_SERVICE_COUNT;