-- ============================================================
-- Customer Intelligence Analytics Platform
-- ANALYTICS - Customer Value
-- Grain: one row per customer value segment
-- ============================================================

USE ROLE CUSTOMER_INTELLIGENCE_ROLE;
USE WAREHOUSE CUSTOMER_INTELLIGENCE_WH;
USE DATABASE CUSTOMER_INTELLIGENCE;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW
    CUSTOMER_INTELLIGENCE.ANALYTICS.VW_CUSTOMER_VALUE AS

WITH BASE AS (

    SELECT *
    FROM CUSTOMER_INTELLIGENCE.CORE.CUSTOMER_360_VIEW

),

TOTALS AS (

    SELECT
        COUNT_IF(CHURN_FLAG = 1) AS TOTAL_CHURNED_CUSTOMERS,
        SUM(TOTAL_REVENUE) AS TOTAL_REVENUE_ALL_CUSTOMERS,
        SUM(IFF(CHURN_FLAG = 1, MONTHLY_CHARGE, 0))
            AS TOTAL_CHURNED_MONTHLY_REVENUE
    FROM BASE

)

SELECT

    b.CUSTOMER_VALUE_SEGMENT,
    b.CLTV_QUARTILE,

    COUNT(DISTINCT b.CUSTOMER_ID) AS CUSTOMERS,

    COUNT_IF(b.CHURN_FLAG = 1) AS CHURNED_CUSTOMERS,

    ROUND(
        COUNT_IF(b.CHURN_FLAG = 1)
        / NULLIF(COUNT(DISTINCT b.CUSTOMER_ID), 0),
        4
    ) AS CHURN_RATE,

    ROUND(
        COUNT_IF(b.CHURN_FLAG = 1)
        / NULLIF(MAX(t.TOTAL_CHURNED_CUSTOMERS), 0),
        4
    ) AS CHURN_CONTRIBUTION,

    -- Customer value
    ROUND(AVG(b.CLTV), 2) AS AVG_CLTV,
    MIN(b.CLTV) AS MIN_CLTV,
    MAX(b.CLTV) AS MAX_CLTV,

    -- Revenue
    ROUND(AVG(b.MONTHLY_CHARGE), 2) AS AVG_MONTHLY_CHARGE,
    ROUND(AVG(b.TOTAL_REVENUE), 2) AS AVG_TOTAL_REVENUE,

    ROUND(SUM(b.TOTAL_REVENUE), 2) AS TOTAL_SEGMENT_REVENUE,

    ROUND(
        SUM(b.TOTAL_REVENUE)
        / NULLIF(MAX(t.TOTAL_REVENUE_ALL_CUSTOMERS), 0),
        4
    ) AS REVENUE_SHARE,

    -- Revenue associated with customers already churned
    ROUND(
        SUM(IFF(b.CHURN_FLAG = 1, b.MONTHLY_CHARGE, 0)),
        2
    ) AS CHURNED_MONTHLY_REVENUE,

    ROUND(
        SUM(IFF(b.CHURN_FLAG = 1, b.MONTHLY_CHARGE, 0))
        / NULLIF(MAX(t.TOTAL_CHURNED_MONTHLY_REVENUE), 0),
        4
    ) AS CHURNED_MONTHLY_REVENUE_SHARE,

    -- Lifecycle
    ROUND(AVG(b.TENURE_IN_MONTHS), 2) AS AVG_TENURE_MONTHS

FROM BASE b

CROSS JOIN TOTALS t

GROUP BY
    b.CUSTOMER_VALUE_SEGMENT,
    b.CLTV_QUARTILE

ORDER BY
    b.CLTV_QUARTILE;