-- ============================================================
-- Customer Intelligence Analytics Platform
-- ANALYTICS - Churn Reasons
-- Grain: one row per churn category / churn reason
-- Only customers with observed churn
-- ============================================================

USE ROLE CUSTOMER_INTELLIGENCE_ROLE;
USE WAREHOUSE CUSTOMER_INTELLIGENCE_WH;
USE DATABASE CUSTOMER_INTELLIGENCE;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW
    CUSTOMER_INTELLIGENCE.ANALYTICS.VW_CHURN_REASONS AS

WITH CHURNED_BASE AS (

    SELECT *
    FROM CUSTOMER_INTELLIGENCE.CORE.CUSTOMER_360_VIEW
    WHERE CHURN_FLAG = 1

),

TOTALS AS (

    SELECT COUNT(*) AS TOTAL_CHURNED_CUSTOMERS
    FROM CHURNED_BASE

)

SELECT
    b.CHURN_CATEGORY,
    b.CHURN_REASON,

    COUNT(DISTINCT b.CUSTOMER_ID) AS CHURNED_CUSTOMERS,

    ROUND(
        COUNT(DISTINCT b.CUSTOMER_ID)
        / NULLIF(MAX(t.TOTAL_CHURNED_CUSTOMERS), 0),
        4
    ) AS CHURN_SHARE,

    ROUND(AVG(b.TENURE_IN_MONTHS), 2) AS AVG_TENURE_MONTHS,

    ROUND(AVG(b.MONTHLY_CHARGE), 2) AS AVG_MONTHLY_CHARGE,

    ROUND(AVG(b.TOTAL_REVENUE), 2) AS AVG_TOTAL_REVENUE,

    ROUND(AVG(b.CLTV), 2) AS AVG_CLTV,

    ROUND(AVG(b.SATISFACTION_SCORE), 2) AS AVG_SATISFACTION_SCORE

FROM CHURNED_BASE b

CROSS JOIN TOTALS t

GROUP BY
    b.CHURN_CATEGORY,
    b.CHURN_REASON

ORDER BY
    CHURNED_CUSTOMERS DESC;