-- ============================================================
-- Customer Intelligence Analytics Platform
-- CORE - Final Validation
-- ============================================================

USE ROLE CUSTOMER_INTELLIGENCE_ROLE;
USE WAREHOUSE CUSTOMER_INTELLIGENCE_WH;
USE DATABASE CUSTOMER_INTELLIGENCE;

-- 1. Grain validation
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT CUSTOMER_ID) AS DISTINCT_CUSTOMERS,
    COUNT(*) - COUNT(DISTINCT CUSTOMER_ID) AS DUPLICATE_ROWS
FROM CUSTOMER_INTELLIGENCE.CORE.CUSTOMER_360_VIEW;


-- 2. Join completeness
SELECT
    COUNT_IF(GENDER IS NULL) AS MISSING_PROFILE,
    COUNT_IF(ZIP_CODE IS NULL) AS MISSING_LOCATION,
    COUNT_IF(CONTRACT IS NULL) AS MISSING_SERVICES,
    COUNT_IF(CUSTOMER_STATUS IS NULL) AS MISSING_SNAPSHOT
FROM CUSTOMER_INTELLIGENCE.CORE.CUSTOMER_360_VIEW;


-- 3. Churn reconciliation
SELECT
    CHURN_LABEL,
    CHURN_VALUE,
    COUNT(*) AS CUSTOMERS
FROM CUSTOMER_INTELLIGENCE.CORE.CUSTOMER_360_VIEW
GROUP BY CHURN_LABEL, CHURN_VALUE
ORDER BY CHURN_VALUE;


-- 4. Revenue reconciliation
SELECT
    SUM(TOTAL_REVENUE) AS CORE_TOTAL_REVENUE
FROM CUSTOMER_INTELLIGENCE.CORE.CUSTOMER_360_VIEW;

SELECT
    SUM(TOTAL_REVENUE) AS RAW_TOTAL_REVENUE
FROM CUSTOMER_INTELLIGENCE.RAW.CHURN_SERVICES;


-- 5. CLTV / value segment validation
SELECT
    CUSTOMER_VALUE_SEGMENT,
    COUNT(*) AS CUSTOMERS,
    MIN(CLTV) AS MIN_CLTV,
    AVG(CLTV) AS AVG_CLTV,
    MAX(CLTV) AS MAX_CLTV
FROM CUSTOMER_INTELLIGENCE.CORE.CUSTOMER_360_VIEW
GROUP BY CUSTOMER_VALUE_SEGMENT
ORDER BY AVG_CLTV;